name: firebase_remote_config_talk
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  confetti: ^0.7.0
  device_frame: ^1.1.0
  flutter:
    sdk: flutter
  flutter_deck: ^0.10.1
  flutter_riverpod: ^2.4.6
  record: ^5.0.1
  riverpod_annotation: ^2.3.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.6
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/ab-testing/
    - assets/images/feature-flagging/
    - assets/images/firebase-conditions/
    - assets/images/firebase-parameters/
    - assets/images/firebase-setup/
    - assets/images/forces/
